### ISSUE TITLE
xcode installation error

### ISSUE THREAD

**Issue by humboldtux** [Microsoft/macos-cookbook#163]
On Mojave, up until recently the xcode recipe was working and i managed to install XCoe 10.0 on my systems.

But chef-client runs started to fail recently:

```
Recipe: macos::disable_software_updates
  * plist[disable automatic software update downloads] action set (up to date)
  * plist[disable automatic software update check] action set (up to date)
  * execute[disable software updates using commandline utility] action run (skipped due to not_if)
Recipe: macos::xcode
  * execute[Disable Gatekeeper] action run
    - execute ["spctl", "--master-disable"]
  * xcode[10.0] action install_gem

    ================================================================================
    Error executing action `install_gem` on resource 'xcode[10.0]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `tr' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/macos/libraries/command_line_tools.rb:15:in `initialize'
    /var/chef/cache/cookbooks/macos/resources/xcode.rb:9:in `new'
    /var/chef/cache/cookbooks/macos/resources/xcode.rb:9:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/macos/recipes/xcode.rb

      6:   xcode node['macos']['xcode']['version']
      7:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/macos/recipes/xcode.rb:6:in `from_file'

    xcode("10.0") do
      action [:install_gem, :install_xcode, :install_simulators]
      default_guard_interpreter :default
      declared_type :xcode
      cookbook_name "macos"
      recipe_name "xcode"
    end

    System Info:
    ------------
    chef_version=14.5.33
    platform=mac_os_x
    platform_version=10.14.1
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]
    program_name=/usr/local/bin/chef-client
    executable=/opt/chef/bin/chef-client


Running handlers:
[2018-11-06T09:39:38+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-11-06T09:39:38+01:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 29 seconds
[2018-11-06T09:39:38+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-11-06T09:39:38+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-11-06T09:39:38+01:00] FATAL: NoMethodError: xcode[10.0] (macos::xcode line 6) had an error: NoMethodError: undefined method `tr' for nil:NilClass
```

I thought it was linked to the release of XCode 10.1 so i forced tho this last version in my attributes file:

```
default['macos']['xcode']['version'] = '10.1'
```

But it didn't help.

**Comment by jazaval** [comment]
@humboldtux I repro'd this earlier, but now I'm having trouble doing so - I think Apple updated the available software updates again. Can you retry?

**Comment by humboldtux** [comment]
Yes, now it is working, for both xcode 10.0 and 10.1.
Thank you for your time.
