### ISSUE TITLE
Simulator install causes net-ssh-4.1.0/lib/net/ssh/buffered_io.rb:102:in `send': closed stream (IOError)

### ISSUE THREAD

**Issue by jazaval** [Microsoft/macos-cookbook#44]
During a `kitchen converge`, the iOS simulator installation will sometimes cause a crash in the net-ssh gem:
```
2018-02-12T19:13:32.6031260Z            * execute[install Xcode 8.2.1] action run
2018-02-12T19:13:32.6047250Z              - execute /opt/chef/embedded/bin/xcversion install '8.2.1'
2018-02-12T19:13:32.6079890Z          
2018-02-12T19:13:34.8773880Z          * xcode[8.2.1] action install_simulators[2018-02-12T11:13:34-08:00] WARN: iOS Simulator list not populated yet
2018-02-12T19:13:34.8789810Z        [2018-02-12T11:13:34-08:00] WARN: iOS Simulator list not populated yet
2018-02-12T19:13:48.7091180Z        
2018-02-12T19:15:42.5665420Z /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/buffered_io.rb:102:in `send': closed stream (IOError)
2018-02-12T19:15:42.5682040Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/buffered_io.rb:102:in `send_pending'
2018-02-12T19:15:42.5698340Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:271:in `block in ev_do_handle_events'
2018-02-12T19:15:42.5714540Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:270:in `each'
2018-02-12T19:15:42.5731160Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:270:in `ev_do_handle_events'
2018-02-12T19:15:42.5747520Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:110:in `ev_select_and_postprocess'
2018-02-12T19:15:42.5764620Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
2018-02-12T19:15:42.5780760Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
2018-02-12T19:15:42.5796890Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
2018-02-12T19:15:42.5812960Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
2018-02-12T19:15:42.5829040Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
2018-02-12T19:15:42.5845080Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:124:in `close'
2018-02-12T19:15:42.5861160Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/transport/ssh.rb:121:in `close'
2018-02-12T19:15:42.5877290Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
2018-02-12T19:15:42.5893410Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:294:in `cleanup!'
2018-02-12T19:15:42.5909550Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:205:in `run_action_in_thread'
2018-02-12T19:15:42.5925830Z 	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

Some mention of this issue in the wild - https://github.com/net-ssh/net-ssh/pull/493 and https://github.com/test-kitchen/test-kitchen/issues/1184

**Comment by jazaval** [comment]
Have not observed except in old build node paradigm. Closing as no repro.
