### ISSUE TITLE
Xcode resource incorrectly assumes Xcode command line tools are installed

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/macos-cookbook#71]
The xcode resource fails to install the `xcode-install` gem when the command line tools are not installed. We need to check for their existence and install them if missing.

```
* chef_gem[xcode-install] action install

      ================================================================================
      Error executing action `install` on resource 'chef_gem[xcode-install]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /opt/chef/embedded/bin/gem install xcode-install -q --no-rdoc --no-ri -v "2.3.1" --source=https://www.rubygems.org --no-document --no-user-install ----
      STDOUT: Successfully installed claide-1.0.2
      Successfully installed slack-notifier-2.3.2
      Successfully installed atomos-0.1.2
      Successfully installed CFPropertyList-2.3.6
      Successfully installed colored2-3.1.2
      Successfully installed nanaimo-0.2.3
      Successfully installed xcodeproj-1.5.6
      Successfully installed rouge-2.0.7
      Successfully installed xcpretty-0.2.8
      Successfully installed terminal-notifier-1.8.0
      Successfully installed terminal-table-1.8.0
      Successfully installed public_suffix-2.0.5
      Successfully installed word_wrap-1.0.0
      Successfully installed tty-screen-0.6.4
      Successfully installed tty-cursor-0.5.0
      Successfully installed tty-spinner-0.8.0
      Successfully installed babosa-1.0.2
      Successfully installed colored-1.2
      Successfully installed commander-fastlane-4.4.6
      Building native extensions.  This could take a while...
      STDERR: ERROR:  Error installing xcode-install:
      	ERROR: Failed to build gem native extension.

          current directory: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.5/ext/unf_ext
      /opt/chef/embedded/bin/ruby -r ./siteconf20180317-1387-v2qc6l.rb extconf.rb
      checking for -lstdc++... *** extconf.rb failed ***
      Could not create Makefile due to some reason, probably lack of necessary
      libraries and/or headers.  Check the mkmf.log file for more details.  You may
      need configuration options.

      Provided configuration options:
      	--with-opt-dir
      	--with-opt-include
      	--without-opt-include=${opt-dir}/include
      	--with-opt-lib
      	--without-opt-lib=${opt-dir}/lib
      	--with-make-prog
      	--without-make-prog
      	--srcdir=.
      	--curdir
      	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
      	--with-static-libstdc++
      	--without-static-libstdc++
      	--with-stdc++lib
      	--without-stdc++lib
      /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
      You have to install development tools first.
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:553:in `try_link0'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:568:in `try_link'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:786:in `try_func'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1013:in `block in have_library'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `block in checking_for'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:955:in `checking_for'
      	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1008:in `have_library'
      	from extconf.rb:6:in `<main>'

      To see why this extension failed to compile, please check the mkmf.log which can be found here:

        /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-14/2.4.0/unf_ext-0.0.7.5/mkmf.log

      extconf failed, exit code 1

      Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.5 for inspection.
      Results logged to /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-14/2.4.0/unf_ext-0.0.7.5/gem_make.out
      ---- End output of /opt/chef/embedded/bin/gem install xcode-install -q --no-rdoc --no-ri -v "2.3.1" --source=https://www.rubygems.org --no-document --no-user-install ----
      Ran /opt/chef/embedded/bin/gem install xcode-install -q --no-rdoc --no-ri -v "2.3.1" --source=https://www.rubygems.org --no-document --no-user-install returned 1
```

**Comment by americanhanko** [comment]
Fixed in #82
